[features]
seeds = false
skip-lint = false
[programs.devnet]
minersweeper = "2AvrHDMx3svcY7LexQx5xPvdC3ZKSZaZ2TXmRG9LFNRv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mateo/.config/solana/id.json"

[scripts]
mine = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Minersweeper.ts"
